"""Deterministic, Confluence-style remediation runbooks.

These scaffolds are built from the engine's findings with zero AI, so they work
offline and for free. The optional `--ai` path (ai.py) and the MCP client can
*enrich* this same structure, but the bones are always here.
"""

from __future__ import annotations

from .models import Cluster, FleetReport, RiskBreakdown

# Concrete, data-derived remediation steps per failing control.
REMEDIATION_STEPS: dict[str, list[str]] = {
    "patch_drift": [
        "Confirm the devices' current patch level against the latest approved build.",
        "Check why the patch ring did not advance (reboot deferral, maintenance window, agent health).",
        "Stage the missing cumulative update to a pilot device in the same role and verify no regressions.",
        "Roll the update out in waves (10% -> 50% -> 100%), forcing a reboot window for always-on devices.",
        "Move chronically-deferred devices to a stricter patch ring with an enforced reboot deadline.",
    ],
    "encryption_off": [
        "Verify the device is MDM-enrolled and reachable before changing disk policy.",
        "Confirm a recovery key escrow exists in the MDM before enabling encryption (avoid lockout).",
        "Trace the source: a shared gold image with encryption disabled will reproduce this on every reimage.",
        "Enable full-disk encryption via MDM policy and confirm the recovery key escrows successfully.",
        "Fix the upstream gold image so future provisioning ships with encryption on by default.",
    ],
    "stale_checkin": [
        "Determine whether the device is intentionally offline (air-gapped booth) or genuinely lost.",
        "For intentionally-offline devices, document an exception and a manual audit cadence.",
        "For others, check network/VPN reachability and the MDM agent service state.",
        "Re-establish the MDM check-in and confirm policy + inventory sync within 24h.",
        "Add an alert for devices exceeding the stale-check-in threshold so this is caught proactively.",
    ],
    "mdm_unenrolled": [
        "Confirm the device should be managed (in-scope asset, not a personal/BYO device).",
        "Enroll the device into MDM and apply the baseline configuration profile.",
        "Verify compliance controls (encryption, EDR, firewall) report after enrollment.",
    ],
    "unmanaged_ring": [
        "Identify why the device is on the unmanaged patch ring.",
        "Reassign it to a managed ring (broad/early) with an enforced reboot policy.",
        "Confirm the next patch cycle reaches the device.",
    ],
    "edr_unhealthy": [
        "Check the EDR agent service status and last telemetry timestamp.",
        "Reinstall or repair the EDR agent and confirm it reports healthy to the console.",
        "Validate the device appears in the EDR coverage report.",
    ],
    "firewall_off": [
        "Confirm no local exception intentionally disabled the firewall.",
        "Re-enable the host firewall via MDM policy and lock the setting.",
    ],
    "secure_boot_off": [
        "Verify hardware/firmware supports secure boot and it is safe to enable.",
        "Enable secure boot in firmware policy; schedule a maintenance reboot.",
    ],
}


def suggest_remediation(control: str) -> list[str]:
    return REMEDIATION_STEPS.get(control, ["Investigate the failing control and apply the org baseline."])


def find_cluster(report: FleetReport, key: str) -> Cluster | None:
    return next((c for c in report.clusters if c.runbook_key == key), None)


def find_device(report: FleetReport, device_id: str) -> RiskBreakdown | None:
    return next((b for b in report.at_risk if b.device_id == device_id), None)


def _frontmatter(title: str) -> str:
    return (
        f"# {title}\n\n"
        "> **DRAFT runbook** generated by Fleet Triage AI from synthetic fleet data.\n"
        "> Review before operational use.\n\n"
    )


def runbook_for_cluster(cluster: Cluster, report: FleetReport) -> str:
    steps = suggest_remediation(cluster.root_cause)
    members = [b for b in report.at_risk if (b.dominant and b.dominant.control == cluster.root_cause)]
    devices = "\n".join(f"| `{b.device_id}` | {b.hostname} | {b.role} | {b.location} | {b.risk} |" for b in members[:20])

    md = _frontmatter(f"Remediation Runbook — {cluster.title}")
    md += (
        f"## Summary\n\n"
        f"**{cluster.affected_count}** device(s) share a dominant fault of "
        f"**{cluster.title.lower()}**, concentrated in **{cluster.correlate}**. "
        f"This runbook remediates the cluster and closes the upstream cause.\n\n"
        f"## Scope\n\n"
        f"| Device ID | Hostname | Role | Location | Risk |\n"
        f"| --- | --- | --- | --- | --- |\n{devices}\n\n"
        f"## Root cause\n\n"
        f"Dominant control: `{cluster.root_cause}`. The strong correlation with "
        f"{cluster.correlate} indicates a systemic source (e.g. a shared image, a "
        f"stalled patch ring, or an offline device class) rather than isolated failures.\n\n"
        f"## Remediation steps\n\n"
    )
    md += "".join(f"{i}. {s}\n" for i, s in enumerate(steps, 1))
    md += (
        "\n## Verification\n\n"
        "- Re-run `fleet-triage scan` and confirm the affected devices drop below the at-risk threshold.\n"
        f"- Confirm the `{cluster.title}` cluster no longer appears in the report.\n\n"
        "## Rollback\n\n"
        "- Each step above is reversible via the same MDM policy surface; revert the policy "
        "assignment and force a sync if a regression is observed on the pilot device.\n"
    )
    return md


def runbook_for_device(device: RiskBreakdown) -> str:
    md = _frontmatter(f"Remediation Runbook — {device.hostname}")
    md += (
        f"## Summary\n\n`{device.device_id}` ({device.role}, {device.location}) scored "
        f"**{device.risk}** ({device.band}). Failing controls below.\n\n"
        f"## Failing controls\n\n| Control | Points | Detail |\n| --- | --- | --- |\n"
    )
    md += "".join(f"| `{f.control}` | {f.points} | {f.detail} |\n" for f in device.factors)
    md += "\n## Remediation steps\n\n"
    seen: set[str] = set()
    n = 1
    for f in sorted(device.factors, key=lambda x: x.points, reverse=True):
        for step in suggest_remediation(f.control):
            if step not in seen:
                md += f"{n}. {step}\n"
                seen.add(step)
                n += 1
    md += (
        "\n## Verification\n\n- Re-run `fleet-triage scan` and confirm the device's risk drops below the threshold.\n"
        "\n## Rollback\n\n- Revert the relevant MDM policy assignment and force a device sync.\n"
    )
    return md
